YCloudYUSA/yusaopeny

- composer.json
> fix: Add dev entity embed with PHP 8.1 fixes

- composer.json
> feat: Migrate Activity Finder

- composer.json
> Apply VERF patch

- composer.json
- openy.packages.yml
https://yusa.atlassian.net/browse/DS-20 (Main)
https://fivejars.atlassian.net/browse/YUOPENY-10 (internal)
> Private pages [YUOPENY-10]

- README.md
- RoboFile.php
- SMOKE_TESTS.md
- behat.local.yml
- build/openy-digital-ocean.sh
- config/README.md
- config/install/system.site.yml
- openy.info.yml
- openy.install
- openy.packages.yml
- openy.post_update.php
- openy.profile
- src/Form/ConfigureProfileForm.php
- src/Form/SearchSelectForm.php
- src/Form/TermsOfUseForm.php
- src/Form/ThemeSelectForm.php
- src/Form/UploadFontMessageForm.php
- themes/README.md
- themes/openy_themes/openy_admin/config/schema/openy_admin.schema.yml
- themes/openy_themes/openy_admin/openy_admin.info.yml
Original Issue, this PR is going to fix: https://yusa.atlassian.net/browse/DS-241
> feat: Mass renaming safe places from Open Y to WS

- composer.json
as per https://www.drupal.org/project/webform/issues/3305679
> Remove getEntitiesToView patch

- composer.json
Addresses: https://yusa.atlassian.net/browse/DS-279
Related: https://git.drupalcode.org/project/groupexpro/-/compare/1.0.6...1.0.x?from_project_id=75887&straight=false
> feat: Add open-y-subprojects/openy_daxko_gxp_syncer

- composer.json
> DS-456: Fixed patches

- composer.json
[DS-467](https://yusa.atlassian.net/browse/DS-467)
> [DS-467] Fix Amenities filter on the locations list page

- composer.json
> Update anpolimus patch 1 PR #39

- composer.json
> feat: Test Drupal 9 Twig 3

- composer.json
https://yusa.atlassian.net/browse/DS-417
> DS-417 Open Y Map 2.x version added to composer.json

- RoboFile.php
> [Drupal 10] Update RoboFile.php

- src/Form/ThemeSelectForm.php
Original Issue, this PR is going to fix: https://yusa.atlassian.net/browse/DS-667
> Change default theme to Carnation

- composer.json
https://yusa.atlassian.net/jira/software/projects/DS/issues/DS-677
> fix: add patch for entity clone.

- composer.json
> feat!: get rid of development, unused packages

- assets/installation-profile-ui.js
- openy.libraries.yml
Fix the issue with the installation of the profile on the **Selection Installation type** step
> [DS-709] Fix issue with JS for profile installation process

- openy.info.yml
> feat: bump version for dev release

- composer.json
Incorporates: https://github.com/YCloudYUSA/yusaopeny_activity_finder/releases/tag/4.2.0
Backported-by: @shuklina
Backports: https://github.com/YCloudYUSA/yusaopeny_activity_finder/pull/20
Original Issue, this PR is going to fix: 
> feat: Allow UTM codes in AF

- composer.json
Addresses: https://yusa.atlassian.net/browse/DS-881
> feat: add confi 3.1

- composer.json
We have 2 rows with adding the the open-y-subprojects/openy_custom module . In this PR removed an old version of the open-y-subprojects/openy_custom module that was accidentally added. 
> Fix version of the open-y-subprojects/openy_custom module

- composer.json
_This is my first PR. Sorry if I have filled this out wrong_
Original Issue, this PR is going to fix: https://github.com/YCloudYUSA/yusaopeny/issues/90
- Run composer require ycloudyusa/yusaopeny:10.2.x-dev@dev -W on an existing site running Drupal 9
> Allow hal to be installed on Drupal 9 

- openy.install
https://www.drupal.org/project/openy_carnation/issues/3376676#comment-15163877
This resolves an update issue where the site will error with a WSOD and:
> Drupal\Component\Plugin\Exception\PluginNotFoundException: The "error_page" plugin does not exist. Valid plugin IDs for Drupal\Core\Condition\ConditionManager are: ...
This is due to a removed dependency, and we attempted to remove the config in the theme but apparently that's not possible.
---
> fix: Remove unused theme config

- composer.json
> Updated entity_clone

- composer.json
https://github.com/YCloudYUSA/y_lb/releases/tag/2.3.0 
https://github.com/YCloudYUSA/y_lb/releases/tag/2.3.1
> feat: Update y_lb to add meta and other new features

- composer.json
Original Issue, this PR is going to fix: https://yusa.atlassian.net/browse/DS-907 and https://yusa.atlassian.net/browse/DS-909
> feat: New Alerts

- composer.json
> feat: add commerce_cart_api to lenient to unblock us

- openy.installation_types.yml
- openy.packages.yml
Original Issue, this PR is going to fix: https://yusa.atlassian.net/jira/software/projects/DS/issues/DS-509?filter=myopenissues
> feat: DS-509 - Basic Package

- composer.json
Addressing: https://yusaslackinstance.slack.com/archives/C03E6SQQ0Q5/p1696509259963409
Ensure media_entity_document is still here
> fix(cleanup): remove duplicate

- src/Form/TermsOfUseForm.php
Original Issue, this PR is going to fix: [DS-926](https://yusa.atlassian.net/browse/DS-926)
Was added the new Terms & Conditions options
> [DS-926] [Demo Content] Update Terms & Conditions

- composer.json
Addresses: https://yusa.atlassian.net/browse/DS-1100
> fix: Fix for openy_repeat so it can be used as a Schedules page filter

- composer.json
- openy.info.yml
> feat: Paragraphs => LB blocks

- composer.json
Addresses: https://yusa.atlassian.net/browse/DS-748
http://profile.openy.cibox.tools/build4466/test
> fix: DS-748 - [CKEditor 5] Unable to add external video (youtube/vimeo)

- RoboFile.php
- composer.json
- openy.packages.yml
- openy.profile
> V3.x y lb demo content distro no paragraphs

- composer.json
> Bump version of the Openy Features module in composer.json

- composer.json
> fix: add "caret version" to y_lb

- openy.profile
> feat: Setup a new homepage

- RoboFile.php
- composer.json
- openy.packages.yml
- openy.profile
> Y-LB v3 + Demo content [v3_demo_main]

- composer.json
> feat: add module ws_promotion to composer

- README.md
Original Issue, this PR is going to fix: none
> docs: Switch to main branch

- composer.json
Original Issue, this PR is going to fix: https://yusa.atlassian.net/browse/DS-1190
> feat: add patch for to fix save sub-block of the block in LB 

- composer.json
Original Issue, this PR is going to fix: [DS-1194](https://yusa.atlassian.net/browse/DS-1194)
> [DS-1194] Bump version of the entity_embed module

- composer.json
> fix: remove spaces

- composer.json
> Deprecate League CSV for CSV import issue.

- composer.json
Original Issue, this PR is going to fix: (https://yusa.atlassian.net/browse/DS-1245)
> fix: add patch to inline_entity_form

- openy.packages.yml
(DS-1272)[https://yusa.atlassian.net/browse/DS-1272]
> [DS-1272] Add Y Program & Y Program Subcategory modules to the Open Y packages

- README.md
Add drush site-install instructions and clean everything up.
> Readme drush si

- composer.json
Original Issue, this PR is going to fix: https://yusa.atlassian.net/browse/DS-1099
> DS-1099: The yusaopeny_ymca360 module for integrating with YMCA 360 is being added

- composer.json
Original Issue, this PR is going to fix: [DS-723](https://yusa.atlassian.net/browse/DS-723)
> [DS-723] Integrate a functionality of the CKEditor Bootstrap Buttons module to Editor Advanced Link module

- composer.json
Fixed in https://www.drupal.org/project/entity_clone/releases/2.0.0-beta5 https://www.drupal.org/project/entity_clone/issues/3050027#comment-15523006
> Remove entity_clone patch

- openy.install
> fix: Remove cache clear

- composer.json
Original Issue, this PR is going to fix: [DS-1437](https://yusa.atlassian.net/browse/DS-1437)
> feat: Bump y_lb

- composer.json
Caused-by: https://github.com/open-y-subprojects/openy_map/pull/78
Discussion: https://yusaslackinstance.slack.com/archives/C03E6SQQ0Q5/p1714501901336649?thread_ts=1712762074.187279&cid=C03E6SQQ0Q5
> feat: Add multilanguage support to openy_map

- composer.json
bumped major release, cause I don't recall if we use other icons in disto https://github.com/YCloudYUSA/y_lb/releases/tag/3.5.0
> Feat: optimized icons

- composer.json
https://www.drupal.org/project/plugin/issues/2647312#comment-15595424
New release broke plugin patch. [8.x-2.12](https://www.drupal.org/project/plugin/releases/8.x-2.12) released 1 May 2024
> Update drupal/plugin patch

- composer.json
- openy.info.yml
```
" [error]  ArgumentCountError: Too few arguments to function Drupal\\openy_data_wrapper\\DataWrapper::__construct(), 6 passed and exactly 7 expected in Drupal\\openy_data_wrapper\\DataWrapper->__construct() (line 89 of /home/jenkins/workspace/SANDBOX_CARNATION_CUSTOM/build/docroot/modules/contrib/openy_custom/openy_data_wrapper/src/DataWrapper.php) #0 [internal function]: Drupal\\openy_data_wrapper\\DataWrapper->__construct()",
```
If there is a new feature or this is a bug fix - use `main` branch. We'll tag for release if the bug is critical ASAP or tag for release next bug fix release until the …
> fix: OpenY Map 5.2 needed

- composer.json
Original Issue, this PR is going to fix: [DS-1471](https://yusa.atlassian.net/browse/DS-1471)
> [DS-1471] Fix error during creating nodes and adding blocks to LB

- composer.json
Discussion: https://yusaslackinstance.slack.com/archives/C03E6SQQ0Q5/p1716294021735249
> feat: Activity Finder with Colorway support

- composer.json
Remove old patch, committed in https://github.com/ynorth-projects/openy_repeat/pull/37
Folks who need to remove this before this hits can use:
```
"patches-ignore": {
"ycloudyusa/yusaopeny": {
"ynorth-projects/openy_repeat": {
"Fix for openy_repeat so it can be used as a Schedules page filter https://yusa.atlassian.net/browse/DS-1100": "https://github.com/ynorth-projects/openy_repeat/compare/main...seattleymca:YGSSLA-396.diff"
}
},
```
> Remove outdated openy_repeat patch

- composer.json
Original Issue, this PR is going to fix: [issuecomment-2150407387](https://github.com/open-y-subprojects/openy_custom/pull/75#issuecomment-2150407387)
You can find here https://github.com/open-y-subprojects/openy_custom/pull/73#issue-2330547080
> [DS-1471] Apply patch for Redirection module

- composer.json
- openy.info.yml
Original Issue, this PR is going to fix: [DS-1310](https://yusa.atlassian.net/browse/DS-1310)
> [DS-1310] Add and enable the CKEditor 5 Paste Filter module

- composer.json
Caused-by: https://yusa.atlassian.net/browse/DS-1358
> feat: Bump openy_repeat

- composer.json
Original Issue, this PR is going to fix: https://www.drupal.org/project/embed/issues/3466933
> fix: embed failing on D10.2

- composer.json
With Drupal 10.2 the existing patch didn't work, but this one does.
```
Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException: The "ckeditor5_codeBlock" CKEditor 5 plugin definition is configurable, has non-empty default configuration but has no config schema. Config schema is required for validation. in Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition->validateDrupalAspects() (line 186 of core/modules/ckeditor5/src/Plugin/CKEditor5PluginDefinition.php).
```
See https://www.drupal.org/project/ckeditor5_font/issues/3368736#comment-15678064
If there is a new feature or this is a bug fix - use `main` branch. We'll tag for release if the bug is critical ASAP or tag for release next bug …
> Update ckeditor5_font patch

- openy.installation_types.yml
- openy.packages.yml
- openy.profile
- src/Form/UploadFontMessageForm.php
[Small Y Component Prep](https://yusa.atlassian.net/browse/DS-1602)
Requires https://www.drupal.org/project/ws_small_y/issues/3469220
> DS-1602 feat: Add initial Small Y functionality.

- composer.json
> fix: bootstrap_layout_builder

- composer.json
See https://www.drupal.org/project/link_attributes/releases/2.0.0
> There are No backwards compatibility changes however this is a new sub-module for adding attributes to menu links.
Supporting work on https://yusa.atlassian.net/browse/DS-1650
> Allow updating link_attributes to 2.x

- composer.json
See https://www.drupal.org/project/bootstrap_styles/issues/3469863#comment-15775339
Related to #211 
> Lock boostrap_styles to prevent issues until 10.3

- composer.json
- openy.info.yml
Original Issue, this PR is going to fix: [DS-1771](https://yusa.atlassian.net/browse/DS-1771)
> [DS-1771] Update PHP requirement to v8.3

- composer.json
- openy.info.yml
QA area
todo: on @podarok and @svicervlad  - to  upgrade PHP on build server to 8.3
> feat!: min PHP 8.3

- openy.profile
Original Issue, this PR is going to fix: [DS-1545](https://yusa.atlassian.net/browse/DS-1545)
> [DS-1545] Add a profile name to the 'core.extension.module' list

- .github/PULL_REQUEST_TEMPLATE.md
Caused-by: https://github.com/YCloudYUSA/yusaopeny/tree/drupal10.3bugfixes
> feat: Update PULL_REQUEST_TEMPLATE.md

- composer.json
**Issue:** https://jet-dev.atlassian.net/browse/ITCR-647
**openy_repeat:** https://www.drupal.org/project/openy_repeat/releases/2.7.2
> [ITCR-647] Update module openy_repeat to 2.7.2 v.

- composer.json
> [ITCP-173] Fix burger button on the mobile

- composer.json
> fix: issue https://www.drupal.org/project/drupal/issues/3458067

- openy.info.yml
> Drupal10.3bugfixes into main

- composer.json
> fix: [ITCR-742] Update openy_features

- composer.json
This PR updates the composer.json to use the official Drupal.org package of the [openy_node_session](https://www.drupal.org/project/openy_node_session/releases/2.1.2) and [openy_pef_gxp_sync]( https://www.drupal.org/project/openy_pef_gxp_sync/releases/1.1.10) modules, instead of the previous custom GitHub-based package.
Both modules were migrated to Drupal.org with full commit history:
openy_node_session: https://www.drupal.org/project/openy_node_session
openy_pef_gxp_sync: https://www.drupal.org/project/openy_pef_gxp_sync
-  [ ] Check that the source of both modules is Drupal.org (type: package, url: https://packages.drupal.org/8).
- openy_node_session
- openy_pef_gxp_sync
> Migrate openy_node_session, openy_pef_gxp_sync modules on the Drupal.org

- openy.info.yml
Latest release before Drupal 10.4 maintanence release
> feat: Update openy.info.yml - bump version for the point release

- composer.json
> feat: Introduce ws_outsiders

- composer.json
- openy.info.yml
- src/Form/ConfigureProfileForm.php
> Drupal 11 upgrade: staged changes

- composer.json
> fix: use drupal/ymca_sync

- composer.json
> feat: add "drupal/core-composer-scaffold": "~11.0.13",

- openy.info.yml
fix for https://github.com/open-y-subprojects/openy_features/pull/98
> fix: remove ckeditor5_font from deps

- composer.json
> feat: alow beta and rc releases for openy_carnation

- composer.json
> feat: Drupal 11 upgrade path

- composer.json
https://github.com/YCloudYUSA/yusaopeny/pull/289#discussion_r2300314653 to make sure composer installs working versions of theme
> Update composer.json set minimal openy_carnation version to beta3

- src/Form/ConfigureProfileForm.php
internal ticker: https://jet-dev.atlassian.net/browse/ITCR-821
> fix: back MissingDependencyException throw, dependencies already fixed in yusaopeny 11
